name: example
description: rby_widgets example

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  rby_widgets:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true