name: rby_widgets
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_image: ^4.1.4
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.2
  sliver_tools: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: